# Generated by Django 2.0.1 on 2018-01-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_code', models.CharField(max_length=128, verbose_name='Kod producenta')),
                ('name', models.CharField(max_length=256, verbose_name='Nazwa')),
                ('price_net', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Cena netto')),
                ('quantity', models.IntegerField(verbose_name='Stan')),
                ('vat_value', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Stawka VAT')),
            ],
        ),
    ]
